### ISSUE TITLE
gotype fails to include other files in the same package

### ISSUE THREAD

**Issue by jarcoal** [sirreal/SublimeLinter-contrib-gotype#1]
Really love this plugin, but it has one fatal flaw which is that when passing gotype a single filename, it will ignore other files in the same package, so you get undeclared name errors constantly.

It seems to me that you could locate the directory the file is in, run `gotype -e <dir>`, then filter the errors that it dumps out to only that file.

**Comment by rasky** [comment]
I don't see any current problem with long import names, so I'm closing this.
